const vehicles=[['DEL 427 AA','Toyota Camry','Dr. E. Okafor','Faculty of Science'],['ABK 981 KD','Honda Accord','Chisom Nwosu','Management Science'],['DEL 112 BR','Lexus RX 350','Prof. T. Igho','Faculty of Science'],['ASB 620 RT','Toyota Corolla','Uche Eze','Management Science'],['DEL 806 LM','Hyundai Elantra','Sarah Ede','Faculty of Science']];
const body=document.querySelector('#vehicles-body');
function renderVehicles(items=vehicles){body.innerHTML=items.map(v=>`<tr><td><b>${v[0]}</b></td><td>${v[1]}</td><td>${v[2]}</td><td><span class="location">${v[3]}</span></td><td><span class="badge in">Active</span></td></tr>`).join('')};renderVehicles();
async function loadVehicles(){const response=await fetch('/api/vehicles');if(!response.ok)return;const data=await response.json();vehicles.splice(0,vehicles.length,...data.vehicles.map(v=>[v.plate,v.model,v.owner_name,v.faculty]));renderVehicles()}
let signedInUserName='Administrator';
function updateGreeting(){const hour=new Date().getHours();const salutation=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';const firstName=signedInUserName.trim().split(/\s+/)[0]||'Administrator';document.querySelector('#page-title').textContent=`${salutation}, ${firstName}`}
async function applyRoleAccess(){const response=await fetch('/api/session');if(!response.ok){location.href='/login';return}const {user}=await response.json();signedInUserName=user.name;updateGreeting();document.querySelector('.profile b').textContent=user.name;document.querySelector('.profile small').textContent=user.role.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());document.querySelector('.avatar').textContent=user.name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase();const restricted={security_officer:['vehicles','allocations','reports','users'],vehicle_owner:['spaces','allocations','checkin','reports','users']};(restricted[user.role]||[]).forEach(id=>document.querySelectorAll(`[data-page="${id}"],a[href="#${id}"]`).forEach(link=>link.closest('a,button')?.remove()));if(user.role!=='super_admin')document.querySelectorAll('[href="#users"],#open-settings').forEach(element=>element?.remove())}
loadVehicles();applyRoleAccess();
document.querySelectorAll('[data-page]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const id=link.dataset.page;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector('#'+id).classList.add('active-page');document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.querySelector('#page-kicker').textContent=id==='dashboard'?'OVERVIEW':id.toUpperCase();if(id==='dashboard')updateGreeting();else document.querySelector('#page-title').textContent=link.textContent.trim().replace(/\d+/,'');window.scrollTo(0,0)}));
const sidebar=document.querySelector('.sidebar');const menuBackdrop=document.createElement('button');menuBackdrop.className='menu-backdrop';menuBackdrop.type='button';menuBackdrop.setAttribute('aria-label','Close navigation menu');document.body.append(menuBackdrop);function closeMobileMenu(){sidebar.classList.remove('open');menuBackdrop.classList.remove('show')}document.querySelector('.mobile-menu').onclick=()=>{const isOpen=sidebar.classList.toggle('open');menuBackdrop.classList.toggle('show',isOpen)};menuBackdrop.onclick=closeMobileMenu;
const modal=document.querySelector('#vehicle-modal');document.querySelector('#open-register').onclick=()=>modal.showModal();document.querySelector('#open-register-2').onclick=()=>modal.showModal();
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
document.querySelector('#vehicle-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const response=await fetch('/api/vehicles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate:f.get('plate'),model:f.get('model'),owner_name:f.get('owner'),faculty:f.get('faculty'),category:f.get('category'),colour:f.get('colour')})});const data=await response.json();if(!response.ok){toast(data.error||'Could not register vehicle');return}await loadVehicles();modal.close();toast('Vehicle registered successfully')});
document.querySelector('#vehicle-search').oninput=e=>{let q=e.target.value.toLowerCase();renderVehicles(vehicles.filter(v=>v.join(' ').toLowerCase().includes(q)))};
const gate=document.querySelector('#gate-modal');let checkingOut=false;function openGate(out){checkingOut=out;document.querySelector('#gate-title').textContent=out?'Vehicle check-out':'Vehicle check-in';document.querySelector('#gate-copy').textContent=out?'Confirm the departing vehicle to release its space.':'Enter a registration number to assign a space.';document.querySelector('#gate-submit').textContent=out?'Confirm check-out':'Confirm check-in';document.querySelector('#space-field').style.display=out?'none':'block';gate.showModal()}document.querySelector('#open-checkin').onclick=()=>openGate(false);document.querySelector('#open-checkout').onclick=()=>openGate(true);document.querySelector('#gate-form').addEventListener('submit',async e=>{e.preventDefault();const plate=document.querySelector('#gate-plate').value.toUpperCase();const response=await fetch(`/api/gate/${checkingOut?'checkout':'checkin'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate,zone:'Campus',space_code:'Unassigned'})});const data=await response.json();if(!response.ok){toast(data.error||'Gate operation failed');return}if(!checkingOut){let occupied=+document.querySelector('#occupied-number').textContent+1;document.querySelector('#occupied-number').textContent=occupied;document.querySelector('#available-number').textContent=320-occupied}gate.close();toast(`${plate} checked ${checkingOut?'out':'in'} successfully`);e.target.reset()});
new Chart(document.querySelector('#occupancyChart'),{type:'line',data:{labels:['7 AM','8 AM','9 AM','10 AM','11 AM','12 PM','1 PM'],datasets:[{data:[42,88,139,181,205,192,186],borderColor:'#65409a',backgroundColor:'rgba(101,64,154,.15)',fill:true,tension:.42,pointRadius:3,pointBackgroundColor:'#f4cb3c',borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{displayMode:'index',intersect:false}},scales:{x:{grid:{display:false},ticks:{color:'#000',font:{size:11}}},y:{beginAtZero:true,max:240,ticks:{stepSize:60,color:'#000',font:{size:11}},grid:{color:'#ded8e6'}}}}});
function showPage(id,title){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector('#'+id).classList.add('active-page');document.querySelectorAll('nav a').forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+id));document.querySelector('#page-kicker').textContent=id.toUpperCase();document.querySelector('#page-title').textContent=title;document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
document.querySelectorAll('a[href="#users"],a[href="#activity"]').forEach(link=>link.onclick=e=>{e.preventDefault();showPage(link.getAttribute('href').slice(1),link.textContent.trim())});
document.querySelector('#open-settings').onclick=()=>showPage('settings','System settings');
const settingsFields=['visitor-limit'];
settingsFields.forEach(id=>{const saved=localStorage.getItem('delspark-'+id);if(saved!==null)document.querySelector('#'+id).value=saved});
document.querySelector('#save-settings').onclick=()=>{settingsFields.forEach(id=>localStorage.setItem('delspark-'+id,document.querySelector('#'+id).value));toast('System settings saved successfully')};
function downloadFile(filename,type,contents){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([contents],{type}));link.download=filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
document.querySelector('#export-audit').onclick=()=>{downloadFile('delspark-audit-log.csv','text/csv','Action,User,Detail,Time\nVehicle checked in,Security Officer,DEL 427 AA assigned to Science Zone A,09:42 AM\nVehicle registered,Admin Officer,Added ABK 981 KD for Chisom Nwosu,Yesterday');toast('Audit log exported successfully')};
document.querySelector('#backup-data').onclick=()=>{const backup={system:'DELSPARK',generatedAt:new Date().toISOString(),vehicles,settings:{visitorLimit:document.querySelector('#visitor-limit').value}};downloadFile('delspark-backup.json','application/json',JSON.stringify(backup,null,2));toast('System backup created successfully')};
document.querySelector('#invite-user').onclick=async()=>{const name=prompt('New user full name:');if(!name)return;const email=prompt('New user email:');const password=prompt('Temporary password (8 or more characters):');const role=prompt('Role: super_admin, parking_admin, security_officer, or vehicle_owner','parking_admin');if(!email||!password||!role)return;const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password,role,faculty_scope:'All faculties'})});const data=await response.json();toast(response.ok?`Account created for ${name}`:(data.error||'Could not create account'))};
document.querySelector('#manage-users').onclick=()=>toast('User administration controls are available to Super Administrators');
document.querySelectorAll('.report-card .secondary').forEach((button,index)=>button.onclick=()=>{const reports=[['daily-parking-activity.csv','Time,Activity,Count\n09:42 AM,Check-in,1\n09:18 AM,Check-out,1'],['occupancy-summary.csv','Lot,Capacity,Occupied,Available\nFaculty of Science,180,112,68\nManagement Science,140,74,66'],['vehicle-registry.csv','Plate,Vehicle,Owner,Faculty\n'+vehicles.map(v=>v.join(',')).join('\n')]];downloadFile(reports[index][0],'text/csv',reports[index][1]);toast('Report exported successfully')});
const profileMenu=document.querySelector('.profile');profileMenu.classList.add('profile-menu');profileMenu.tabIndex=0;profileMenu.setAttribute('role','button');profileMenu.setAttribute('aria-expanded','false');const profileDropdown=document.createElement('div');profileDropdown.className='profile-dropdown';profileDropdown.innerHTML='<button type="button" aria-label="Sign out">Sign out</button>';profileMenu.append(profileDropdown);const toggleProfileMenu=()=>{const isOpen=profileMenu.classList.toggle('open');profileMenu.setAttribute('aria-expanded',String(isOpen))};profileMenu.addEventListener('click',event=>{if(!event.target.closest('.profile-dropdown'))toggleProfileMenu()});profileMenu.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleProfileMenu()}});profileDropdown.querySelector('button').onclick=async event=>{event.stopPropagation();await fetch('/api/auth/logout',{method:'POST'});location.href='/login'};document.addEventListener('click',event=>{if(!profileMenu.contains(event.target)){profileMenu.classList.remove('open');profileMenu.setAttribute('aria-expanded','false')}});
document.querySelectorAll('button').forEach(button=>{if(!button.onclick&&!button.dataset.page&&!button.closest('form')&&!button.closest('#spaces,#allocations')&&button.id===''){button.addEventListener('click',()=>toast(`${button.textContent.trim()||'Action'} is ready for the next workflow step`))}});
document.querySelectorAll('button[value="cancel"]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();const dialog=button.closest('dialog');if(dialog){dialog.close();dialog.querySelector('form')?.reset();toast('Action cancelled')}}));
const vehicleExportButton=document.querySelector('#vehicles .toolbar .secondary');if(vehicleExportButton)vehicleExportButton.onclick=()=>{downloadFile('delspark-vehicle-registry.csv','text/csv','Plate,Vehicle,Owner,Faculty\n'+vehicles.map(vehicle=>vehicle.join(',')).join('\n'));toast('Vehicle registry exported successfully')};
document.querySelectorAll('#spaces .primary').forEach(button=>button.addEventListener('click',()=>{}));
function showRegistrationToast(message,type){const notice=document.querySelector('#toast');notice.textContent=message;notice.classList.remove('error','success');notice.classList.add(type,'show');setTimeout(()=>notice.classList.remove('show'),3500)}
fetch('/api/session').then(response=>response.ok?response.json():null).then(data=>{if(data?.user?.role==='vehicle_owner'){const ownerField=document.querySelector('[name="owner"]');if(ownerField){ownerField.value=data.user.name;ownerField.readOnly=true;ownerField.required=false}}});
const previousVehicleForm=document.querySelector('#vehicle-form');const registrationForm=previousVehicleForm.cloneNode(true);previousVehicleForm.replaceWith(registrationForm);registrationForm.addEventListener('submit',async event=>{event.preventDefault();const submit=registrationForm.querySelector('button.primary');const fields=new FormData(registrationForm);submit.disabled=true;submit.textContent='Registering…';try{const response=await fetch('/api/vehicles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate:fields.get('plate'),model:fields.get('model'),owner_name:fields.get('owner')||'',faculty:fields.get('faculty'),category:fields.get('category')||'Staff',colour:fields.get('colour')||''})});const type=response.headers.get('content-type')||'';const data=type.includes('application/json')?await response.json():{};if(!response.ok)throw new Error(data.error||'Vehicle registration failed.');await loadVehicles();modal.close();registrationForm.reset();showRegistrationToast('✓ Vehicle registered successfully','success')}catch(error){showRegistrationToast(error.message,'error')}finally{submit.disabled=false;submit.textContent='Register vehicle'}});
const zoneDialog=document.createElement('dialog');zoneDialog.className='zone-dialog';document.body.append(zoneDialog);let activeZoneCard=null,zoneSpaceStates=[];
function renderZoneManager(){const occupied=zoneSpaceStates.filter(Boolean).length;const capacity=zoneSpaceStates.length;zoneDialog.querySelector('#zone-occupied').textContent=occupied;zoneDialog.querySelector('#zone-available').textContent=capacity-occupied;zoneDialog.querySelector('#zone-spaces').innerHTML=zoneSpaceStates.map((occupied,index)=>`<button type="button" class="space-toggle ${occupied?'occupied':'available'}" data-space="${index}">${activeZoneCard.querySelector('h3').textContent.replace('Zone ','')}-${String(index+1).padStart(2,'0')}</button>`).join('');zoneDialog.querySelectorAll('.space-toggle').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.space);zoneSpaceStates[index]=!zoneSpaceStates[index];renderZoneManager()})}
function openZoneManager(card){activeZoneCard=card;const zoneName=card.querySelector('h3').textContent;const faculty=card.querySelector('.zone-label').textContent;const counts=card.querySelector('strong').textContent.match(/(\d+)\s*\/?\s*(\d+)/);const occupied=Number(counts?.[1]||0),capacity=Number(counts?.[2]||0);const saved=JSON.parse(localStorage.getItem(`delspark-zone-${zoneName}`)||'null');zoneSpaceStates=saved?.spaces||Array.from({length:capacity},(_,index)=>index<occupied);zoneDialog.innerHTML=`<form method="dialog"><button class="modal-close" value="cancel" aria-label="Close">×</button><span>ZONE MANAGEMENT</span><h2>${zoneName}</h2><p>${faculty} parking zone. Select a space to switch its availability.</p><div class="zone-summary"><div><b id="zone-occupied">0</b><span>Occupied</span></div><div><b id="zone-available">0</b><span>Available</span></div><div><b>${zoneSpaceStates.length}</b><span>Total spaces</span></div></div><div id="zone-spaces" class="space-manager-grid"></div><p class="zone-key"><i class="occupied"></i> Occupied <i class="available"></i> Available</p><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button type="button" id="save-zone" class="primary">Save zone changes</button></div></form>`;zoneDialog.querySelector('#save-zone').onclick=()=>{const currentOccupied=zoneSpaceStates.filter(Boolean).length;const strong=card.querySelector('strong');strong.innerHTML=`${currentOccupied} <small>/ ${zoneSpaceStates.length}</small>`;card.querySelector('p').textContent='spaces occupied';card.querySelector('.meter i').style.width=`${Math.round(currentOccupied/zoneSpaceStates.length*100)}%`;localStorage.setItem(`delspark-zone-${zoneName}`,JSON.stringify({spaces:zoneSpaceStates}));zoneDialog.close();showRegistrationToast(`✓ ${zoneName} updated successfully`,'success')};renderZoneManager();zoneDialog.showModal()}
document.querySelectorAll('#spaces .text-button').forEach(button=>button.onclick=()=>openZoneManager(button.closest('.zone-card')));
const allocationDialog=document.createElement('dialog');allocationDialog.className='allocation-dialog';document.body.append(allocationDialog);
async function loadAllocations(){const response=await fetch('/api/allocations');if(!response.ok)return;const {allocations}=await response.json();let panel=document.querySelector('#allocation-list');if(!panel){panel=document.createElement('article');panel.id='allocation-list';panel.className='panel allocation-list';document.querySelector('#allocations').append(panel)}panel.innerHTML=allocations.length?`<h3>Active allocations</h3><div class="table-wrap"><table><thead><tr><th>VEHICLE</th><th>OWNER</th><th>ZONE</th><th>SPACE</th><th>ASSIGNED</th></tr></thead><tbody>${allocations.map(item=>`<tr><td><b>${item.plate}</b><small>${item.model}</small></td><td>${item.owner_name}</td><td>${item.zone}</td><td><span class="badge">${item.space_code}</span></td><td>${new Date(item.allocated_at).toLocaleDateString()}</td></tr>`).join('')}</tbody></table></div>`:'<h3>No active allocations</h3><p>Create an allocation to reserve a parking space for a registered vehicle.</p>'}
async function openAllocationDialog(){const response=await fetch('/api/vehicles');if(!response.ok){showRegistrationToast('Unable to load registered vehicles','error');return}const {vehicles:registeredVehicles}=await response.json();if(!registeredVehicles.length){showRegistrationToast('Register a vehicle before creating an allocation','error');return}allocationDialog.innerHTML=`<form method="dialog"><button class="modal-close" value="cancel" aria-label="Close">×</button><span>PARKING ALLOCATION</span><h2>Assign a parking space</h2><p>Reserve a numbered space for a registered vehicle.</p><label>Vehicle<select id="allocation-vehicle">${registeredVehicles.map(vehicle=>`<option value="${vehicle.id}">${vehicle.plate} — ${vehicle.owner_name}</option>`).join('')}</select></label><div class="form-grid"><label>Parking zone<select id="allocation-zone"><option>Zone A</option><option>Zone B</option><option>Zone C</option><option>Zone D</option></select></label><label>Space number<input id="allocation-space" required placeholder="e.g. A-23"></label></div><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button type="button" id="save-allocation" class="primary">Create allocation</button></div></form>`;allocationDialog.querySelector('#save-allocation').onclick=async()=>{const vehicle_id=allocationDialog.querySelector('#allocation-vehicle').value,zone=allocationDialog.querySelector('#allocation-zone').value,space_code=allocationDialog.querySelector('#allocation-space').value.trim();if(!space_code){showRegistrationToast('Enter a parking space number','error');return}const response=await fetch('/api/allocations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicle_id,zone,space_code})});const type=response.headers.get('content-type')||'';const data=type.includes('application/json')?await response.json():{};if(!response.ok){showRegistrationToast(data.error||'Could not create allocation','error');return}allocationDialog.close();await loadAllocations();showRegistrationToast('✓ Parking allocation created successfully','success')};allocationDialog.showModal()}
document.querySelectorAll('#allocations .primary').forEach(button=>button.onclick=openAllocationDialog);loadAllocations();
async function refreshUsers(){const response=await fetch('/api/users');if(!response.ok)return;const {users}=await response.json();document.querySelector('#users-body').innerHTML=users.map(user=>`<tr><td><b>${user.name}</b><small>${user.email}</small></td><td>${user.role.replaceAll('_',' ')}</td><td>${user.faculty_scope}</td><td><span class="badge">${user.active?'Active':'Inactive'}</span></td></tr>`).join('');showRegistrationToast('User list refreshed','success')}
document.querySelector('#manage-users').onclick=refreshUsers;document.querySelector('#invite-user').addEventListener('click',()=>setTimeout(refreshUsers,300));
document.querySelectorAll('.report-card .secondary').forEach((button,index)=>button.onclick=()=>{const reports=['daily','occupancy','vehicles'];window.location.assign(`/api/reports/${reports[index]}`)});
async function refreshActivity(){const response=await fetch('/api/activity');if(!response.ok)return;const {activity}=await response.json();const body=document.querySelector('#activity tbody');if(body)body.innerHTML=activity.map(item=>`<tr><td><span class="badge">${item.action}</span></td><td>${item.user_name}</td><td>${item.detail}</td><td>${new Date(item.created_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="4">No activity recorded yet.</td></tr>'}
refreshActivity();document.querySelector('.help').onclick=()=>showRegistrationToast('Help centre: contact the DELSPARK Super Administrator for support.','success');document.querySelector('.icon-button').onclick=()=>showRegistrationToast('No new notifications.','success');
/* Cancel and close controls must never submit or trigger required-field validation. */
document.addEventListener('click',event=>{const control=event.target.closest('button[value="cancel"],button.modal-close');if(!control)return;const dialog=control.closest('dialog');if(!dialog)return;event.preventDefault();event.stopPropagation();dialog.close();dialog.querySelector('form')?.reset();});
const addSpaceDialog=document.createElement('dialog');addSpaceDialog.className='allocation-dialog';document.body.append(addSpaceDialog);function openAddSpaceDialog(){const cards=[...document.querySelectorAll('.zone-card')];addSpaceDialog.innerHTML=`<form method="dialog"><button class="modal-close" value="cancel" aria-label="Close">×</button><span>PARKING SPACES</span><h2>Add a parking space</h2><p>Add an available numbered space to a zone on this device.</p><label>Parking zone<select id="new-space-zone">${cards.map((card,index)=>`<option value="${index}">${card.querySelector('h3').textContent}</option>`).join('')}</select></label><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button type="button" id="save-new-space" class="primary">Add space</button></div></form>`;addSpaceDialog.querySelector('#save-new-space').onclick=()=>{const card=cards[Number(addSpaceDialog.querySelector('#new-space-zone').value)];const zoneName=card.querySelector('h3').textContent;const stored=JSON.parse(localStorage.getItem(`delspark-zone-${zoneName}`)||'null');const counts=card.querySelector('strong').textContent.match(/(\d+)\s*\/?\s*(\d+)/);const spaces=stored?.spaces||Array.from({length:Number(counts?.[2]||0)},(_,index)=>index<Number(counts?.[1]||0));spaces.push(false);localStorage.setItem(`delspark-zone-${zoneName}`,JSON.stringify({spaces}));const occupied=spaces.filter(Boolean).length;card.querySelector('strong').innerHTML=`${occupied} <small>/ ${spaces.length}</small>`;card.querySelector('.meter i').style.width=`${Math.round(occupied/spaces.length*100)}%`;addSpaceDialog.close();showRegistrationToast(`✓ Space added to ${zoneName}`,'success')};addSpaceDialog.showModal()}document.querySelector('#spaces .primary').onclick=openAddSpaceDialog;
registrationForm.querySelectorAll('button[value="cancel"]').forEach(button=>button.onclick=event=>{event.preventDefault();modal.close();registrationForm.reset();showRegistrationToast('Action cancelled','success')});
document.querySelectorAll('.sidebar a').forEach(link=>link.addEventListener('click',closeMobileMenu));
