const vehicles=[['DEL 427 AA','Toyota Camry','Dr. E. Okafor','Faculty of Science'],['ABK 981 KD','Honda Accord','Chisom Nwosu','Management Science'],['DEL 112 BR','Lexus RX 350','Prof. T. Igho','Faculty of Science'],['ASB 620 RT','Toyota Corolla','Uche Eze','Management Science'],['DEL 806 LM','Hyundai Elantra','Sarah Ede','Faculty of Science']];
const body=document.querySelector('#vehicles-body');
function renderVehicles(items=vehicles){body.innerHTML=items.map(v=>`<tr><td><b>${v[0]}</b></td><td>${v[1]}</td><td>${v[2]}</td><td><span class="location">${v[3]}</span></td><td><span class="badge in">Active</span></td></tr>`).join('')};renderVehicles();
async function loadVehicles(){const response=await fetch('/api/vehicles');if(!response.ok)return;const data=await response.json();vehicles.splice(0,vehicles.length,...data.vehicles.map(v=>[v.plate,v.model,v.owner_name,v.faculty]));renderVehicles()}
async function applyRoleAccess(){const response=await fetch('/api/session');if(!response.ok){location.href='/login';return}const {user}=await response.json();document.querySelector('.profile b').textContent=user.name;document.querySelector('.profile small').textContent=user.role.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());document.querySelector('.avatar').textContent=user.name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase();const restricted={security_officer:['vehicles','allocations','reports','users'],vehicle_owner:['spaces','allocations','checkin','reports','users']};(restricted[user.role]||[]).forEach(id=>document.querySelectorAll(`[data-page="${id}"],a[href="#${id}"]`).forEach(link=>link.closest('a,button')?.remove()));if(user.role!=='super_admin')document.querySelectorAll('[href="#users"],#open-settings').forEach(element=>element?.remove())}
loadVehicles();applyRoleAccess();
document.querySelectorAll('[data-page]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const id=link.dataset.page;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector('#'+id).classList.add('active-page');document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.querySelector('#page-kicker').textContent=id==='dashboard'?'OVERVIEW':id.toUpperCase();document.querySelector('#page-title').textContent=id==='dashboard'?'Good morning, Administrator':link.textContent.trim().replace(/\d+/,'');window.scrollTo(0,0)}));
document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
const modal=document.querySelector('#vehicle-modal');document.querySelector('#open-register').onclick=()=>modal.showModal();document.querySelector('#open-register-2').onclick=()=>modal.showModal();
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
document.querySelector('#vehicle-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const response=await fetch('/api/vehicles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate:f.get('plate'),model:f.get('model'),owner_name:f.get('owner'),faculty:f.get('faculty'),category:f.get('category'),colour:f.get('colour')})});const data=await response.json();if(!response.ok){toast(data.error||'Could not register vehicle');return}await loadVehicles();modal.close();toast('Vehicle registered successfully')});
document.querySelector('#vehicle-search').oninput=e=>{let q=e.target.value.toLowerCase();renderVehicles(vehicles.filter(v=>v.join(' ').toLowerCase().includes(q)))};
const gate=document.querySelector('#gate-modal');let checkingOut=false;function openGate(out){checkingOut=out;document.querySelector('#gate-title').textContent=out?'Vehicle check-out':'Vehicle check-in';document.querySelector('#gate-copy').textContent=out?'Confirm the departing vehicle to release its space.':'Enter a registration number to assign a space.';document.querySelector('#gate-submit').textContent=out?'Confirm check-out':'Confirm check-in';document.querySelector('#space-field').style.display=out?'none':'block';gate.showModal()}document.querySelector('#open-checkin').onclick=()=>openGate(false);document.querySelector('#open-checkout').onclick=()=>openGate(true);document.querySelector('#gate-form').addEventListener('submit',async e=>{e.preventDefault();const plate=document.querySelector('#gate-plate').value.toUpperCase();const response=await fetch(`/api/gate/${checkingOut?'checkout':'checkin'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate,zone:'Campus',space_code:'Unassigned'})});const data=await response.json();if(!response.ok){toast(data.error||'Gate operation failed');return}if(!checkingOut){let occupied=+document.querySelector('#occupied-number').textContent+1;document.querySelector('#occupied-number').textContent=occupied;document.querySelector('#available-number').textContent=320-occupied}gate.close();toast(`${plate} checked ${checkingOut?'out':'in'} successfully`);e.target.reset()});
new Chart(document.querySelector('#occupancyChart'),{type:'line',data:{labels:['7 AM','8 AM','9 AM','10 AM','11 AM','12 PM','1 PM'],datasets:[{data:[42,88,139,181,205,192,186],borderColor:'#65409a',backgroundColor:'rgba(101,64,154,.15)',fill:true,tension:.42,pointRadius:3,pointBackgroundColor:'#f4cb3c',borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{displayMode:'index',intersect:false}},scales:{x:{grid:{display:false},ticks:{color:'#000',font:{size:11}}},y:{beginAtZero:true,max:240,ticks:{stepSize:60,color:'#000',font:{size:11}},grid:{color:'#ded8e6'}}}}});
function showPage(id,title){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector('#'+id).classList.add('active-page');document.querySelectorAll('nav a').forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+id));document.querySelector('#page-kicker').textContent=id.toUpperCase();document.querySelector('#page-title').textContent=title;document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
document.querySelectorAll('a[href="#users"],a[href="#activity"]').forEach(link=>link.onclick=e=>{e.preventDefault();showPage(link.getAttribute('href').slice(1),link.textContent.trim())});
document.querySelector('#open-settings').onclick=()=>showPage('settings','System settings');
const settingsFields=['visitor-limit'];
settingsFields.forEach(id=>{const saved=localStorage.getItem('delspark-'+id);if(saved!==null)document.querySelector('#'+id).value=saved});
document.querySelector('#save-settings').onclick=()=>{settingsFields.forEach(id=>localStorage.setItem('delspark-'+id,document.querySelector('#'+id).value));toast('System settings saved successfully')};
function downloadFile(filename,type,contents){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([contents],{type}));link.download=filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
document.querySelector('#export-audit').onclick=()=>{downloadFile('delspark-audit-log.csv','text/csv','Action,User,Detail,Time\nVehicle checked in,Security Officer,DEL 427 AA assigned to Science Zone A,09:42 AM\nVehicle registered,Admin Officer,Added ABK 981 KD for Chisom Nwosu,Yesterday');toast('Audit log exported successfully')};
document.querySelector('#backup-data').onclick=()=>{const backup={system:'DELSPARK',generatedAt:new Date().toISOString(),vehicles,settings:{visitorLimit:document.querySelector('#visitor-limit').value}};downloadFile('delspark-backup.json','application/json',JSON.stringify(backup,null,2));toast('System backup created successfully')};
document.querySelector('#invite-user').onclick=async()=>{const name=prompt('New user full name:');if(!name)return;const email=prompt('New user email:');const password=prompt('Temporary password (8 or more characters):');const role=prompt('Role: super_admin, parking_admin, security_officer, or vehicle_owner','parking_admin');if(!email||!password||!role)return;const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password,role,faculty_scope:'All faculties'})});const data=await response.json();toast(response.ok?`Account created for ${name}`:(data.error||'Could not create account'))};
document.querySelector('#manage-users').onclick=()=>toast('User administration controls are available to Super Administrators');
document.querySelectorAll('.report-card .secondary').forEach((button,index)=>button.onclick=()=>{const reports=[['daily-parking-activity.csv','Time,Activity,Count\n09:42 AM,Check-in,1\n09:18 AM,Check-out,1'],['occupancy-summary.csv','Lot,Capacity,Occupied,Available\nFaculty of Science,180,112,68\nManagement Science,140,74,66'],['vehicle-registry.csv','Plate,Vehicle,Owner,Faculty\n'+vehicles.map(v=>v.join(',')).join('\n')]];downloadFile(reports[index][0],'text/csv',reports[index][1]);toast('Report exported successfully')});
const profileMenu=document.querySelector('.profile');profileMenu.classList.add('profile-menu');profileMenu.tabIndex=0;profileMenu.setAttribute('role','button');profileMenu.setAttribute('aria-expanded','false');const profileDropdown=document.createElement('div');profileDropdown.className='profile-dropdown';profileDropdown.innerHTML='<button type="button" aria-label="Sign out">Sign out</button>';profileMenu.append(profileDropdown);const toggleProfileMenu=()=>{const isOpen=profileMenu.classList.toggle('open');profileMenu.setAttribute('aria-expanded',String(isOpen))};profileMenu.addEventListener('click',event=>{if(!event.target.closest('.profile-dropdown'))toggleProfileMenu()});profileMenu.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleProfileMenu()}});profileDropdown.querySelector('button').onclick=async event=>{event.stopPropagation();await fetch('/api/auth/logout',{method:'POST'});location.href='/login'};document.addEventListener('click',event=>{if(!profileMenu.contains(event.target)){profileMenu.classList.remove('open');profileMenu.setAttribute('aria-expanded','false')}});
document.querySelectorAll('button').forEach(button=>{if(!button.onclick&&!button.dataset.page&&!button.closest('form')&&!button.closest('#spaces,#allocations')&&button.id===''){button.addEventListener('click',()=>toast(`${button.textContent.trim()||'Action'} is ready for the next workflow step`))}});
document.querySelectorAll('button[value="cancel"]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();const dialog=button.closest('dialog');if(dialog){dialog.close();dialog.querySelector('form')?.reset();toast('Action cancelled')}}));
const vehicleExportButton=document.querySelector('#vehicles .toolbar .secondary');if(vehicleExportButton)vehicleExportButton.onclick=()=>{downloadFile('delspark-vehicle-registry.csv','text/csv','Plate,Vehicle,Owner,Faculty\n'+vehicles.map(vehicle=>vehicle.join(',')).join('\n'));toast('Vehicle registry exported successfully')};
document.querySelectorAll('#spaces .primary,#allocations .primary,#spaces .text-button').forEach(button=>button.addEventListener('click',()=>toast(`${button.textContent.trim()} selected. This action is ready for administrator confirmation.`)));
function showRegistrationToast(message,type){const notice=document.querySelector('#toast');notice.textContent=message;notice.classList.remove('error','success');notice.classList.add(type,'show');setTimeout(()=>notice.classList.remove('show'),3500)}
fetch('/api/session').then(response=>response.ok?response.json():null).then(data=>{if(data?.user?.role==='vehicle_owner'){const ownerField=document.querySelector('[name="owner"]');if(ownerField){ownerField.value=data.user.name;ownerField.readOnly=true;ownerField.required=false}}});
const previousVehicleForm=document.querySelector('#vehicle-form');const registrationForm=previousVehicleForm.cloneNode(true);previousVehicleForm.replaceWith(registrationForm);registrationForm.addEventListener('submit',async event=>{event.preventDefault();const submit=registrationForm.querySelector('button.primary');const fields=new FormData(registrationForm);submit.disabled=true;submit.textContent='Registering…';try{const response=await fetch('/api/vehicles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate:fields.get('plate'),model:fields.get('model'),owner_name:fields.get('owner')||'',faculty:fields.get('faculty'),category:fields.get('category')||'Staff',colour:fields.get('colour')||''})});const type=response.headers.get('content-type')||'';const data=type.includes('application/json')?await response.json():{};if(!response.ok)throw new Error(data.error||'Vehicle registration failed.');await loadVehicles();modal.close();registrationForm.reset();showRegistrationToast('✓ Vehicle registered successfully','success')}catch(error){showRegistrationToast(error.message,'error')}finally{submit.disabled=false;submit.textContent='Register vehicle'}});
